name: rankup_education
description: RankUp Education mobile app for students, parents, and teachers.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  dio: ^5.5.0+1
  drift: ^2.20.2
  file_picker: ^8.1.2
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mobile_scanner: ^5.2.3
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  signalr_netcore: ^1.3.7
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
